const KEYS={trades:'tradingnote.localTrades',deleted:'tradingnote.deletedTrades',batches:'tradingnote.liveBatches',active:'tradingnote.activeLiveBatch',strategies:'tradingnote.strategyVersions.v1'};
const ATTR=[['missedTradeR','漏單'],['earlyExitR','提早出場'],['extraTradeR','額外亂做'],['lateEntryR','太晚進場'],['slippageR','滑價／成本'],['marketDriftR','市場狀態差異']];
const CLASS_LABELS={correct_execution:'符合策略且執行正確',execution_error:'符合策略但執行錯誤',rule_violation:'不符合策略卻進場',missed_trade:'符合策略但漏單'};
const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const readArray=key=>{try{const value=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(value)?value:[]}catch{return[]}};
let localTrades=readArray(KEYS.trades),deleted=new Set(readArray(KEYS.deleted)),batches=readArray(KEYS.batches),strategies=readArray(KEYS.strategies),activeBatch=localStorage.getItem(KEYS.active)||'live-default',trades=[];
if(!batches.length)batches=[{id:'live-default',name:'主要紀錄'}];
function baseKey(trade){return`${trade.source||'TradingNote'}::${trade.row||trade.id||''}::${trade.date||''}`}
function mergeTrades(){const imported=(window.TRADES||[]).filter(trade=>!deleted.has(baseKey(trade))).map((trade,index)=>({...trade,id:trade.id??index+1,origin:'imported',batchId:trade.batchId||'live-default',baseKey:baseKey(trade)}));const local=localTrades.map((trade,index)=>({...trade,id:trade.id??100000+index,origin:'local',batchId:trade.batchId||'live-default'}));trades=[...imported,...local]}
function activeTrades(){return activeBatch==='live-all'?uniqueTrades(trades):trades.filter(trade=>(trade.batchId||'live-default')===activeBatch)}
function identity(trade){return trade.externalId||[trade.date,trade.time,trade.pair,trade.profit,trade.entry].join('::')}
function uniqueTrades(items){const map=new Map();items.forEach(trade=>map.set(identity(trade),trade));return[...map.values()]}
function strategyLabel(id){if(!id)return'未綁定策略';const strategy=strategies.find(item=>String(item.id)===String(id));return strategy?`${strategy.name} ${strategy.version}`:'已刪除的策略版本'}
function classLabel(value){return CLASS_LABELS[value]||'待復盤'}
function gapTotal(trade){return ATTR.reduce((sum,[field])=>sum+Math.max(0,Number(trade[field])||0),0)}
function rLabel(trade){return trade.r==null||!Number.isFinite(Number(trade.r))?'R 未記錄':`${Number(trade.r)>0?'+':''}${Number(trade.r).toFixed(2)}R`}
function esc(value){return String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function save(){localStorage.setItem(KEYS.trades,JSON.stringify(localTrades));localStorage.setItem(KEYS.deleted,JSON.stringify([...deleted]));mergeTrades();render()}
function populateControls(){
 const batch=$('#batchSelect'),previous=activeBatch;batch.innerHTML=[...batches,{id:'live-all',name:'完整紀錄'}].map(item=>`<option value="${esc(item.id)}">${esc(item.name)}</option>`).join('');batch.value=[...batch.options].some(option=>option.value===previous)?previous:'live-default';activeBatch=batch.value;
 const strategyOptions=strategies.map(item=>`<option value="${esc(item.id)}">${esc(strategyLabel(item.id))}</option>`).join(''),filter=$('#strategyFilter'),old=filter.value||'all';filter.innerHTML=`<option value="all">全部版本</option><option value="unassigned">未綁定策略</option>${strategyOptions}`;filter.value=[...filter.options].some(option=>option.value===old)?old:'all';
 const markets=[...new Set(activeTrades().map(trade=>trade.pair).filter(Boolean))].sort(),market=$('#marketFilter'),oldMarket=market.value||'all';market.innerHTML='<option value="all">全部商品</option>'+markets.map(item=>`<option>${esc(item)}</option>`).join('');market.value=markets.includes(oldMarket)?oldMarket:'all';
}
function filtered(){const cls=$('#classFilter').value,strategy=$('#strategyFilter').value,market=$('#marketFilter').value,q=$('#searchInput').value.trim().toLowerCase();return activeTrades().filter(trade=>{const review=trade.reviewClass||'pending',text=[trade.date,trade.time,trade.pair,trade.setup,trade.review,strategyLabel(trade.strategyVersionId)].join(' ').toLowerCase();return(cls==='all'||review===cls)&&(strategy==='all'||(strategy==='unassigned'?!trade.strategyVersionId:String(trade.strategyVersionId||'')===strategy))&&(market==='all'||trade.pair===market)&&(!q||text.includes(q))})}
function metrics(){const all=activeTrades(),reviewed=all.filter(trade=>trade.reviewClass),pending=all.length-reviewed.length,correct=reviewed.filter(trade=>trade.reviewClass==='correct_execution').length,aligned=reviewed.filter(trade=>['correct_execution','execution_error','missed_trade'].includes(trade.reviewClass)).length,gap=all.reduce((sum,trade)=>sum+gapTotal(trade),0);$('#pendingHero').innerHTML=`${pending}<small>筆待復盤</small>`;$('#metrics').innerHTML=[['待復盤',pending,`${all.length} 筆總紀錄`,'warn'],['完成率',all.length?`${(reviewed.length/all.length*100).toFixed(1)}%`:'—',`${reviewed.length} 筆已完成`,''],['執行正確',reviewed.length?`${(correct/reviewed.length*100).toFixed(1)}%`:'—',`${correct} 筆正確`,'pos'],['符合策略機會',reviewed.length?`${(aligned/reviewed.length*100).toFixed(1)}%`:'—','包含執行錯誤與漏單',''],['已歸因損失',gap?`-${gap.toFixed(2)}R`:'—','六種原因合計',gap?'neg':'']].map(item=>`<article class="${item[3]}"><span>${item[0]}</span><b>${item[1]}</b><small>${item[2]}</small></article>`).join('')}
function renderRows(){const items=filtered().sort((a,b)=>`${b.date||''} ${b.time||''}`.localeCompare(`${a.date||''} ${a.time||''}`));$('#reviewTableWrap').hidden=!items.length;$('#emptyState').hidden=!!items.length;$('#reviewRows').innerHTML=items.map(trade=>{const missed=trade.recordType==='missed_opportunity'||trade.reviewClass==='missed_trade',key=trade.origin==='local'?`local:${trade.localId}`:`imported:${encodeURIComponent(trade.baseKey)}`;return`<tr><td><b>${esc(trade.date||'-')}</b><small>${esc(trade.time||'')}</small></td><td><b>${esc(trade.pair||'-')}</b><small>${esc(trade.setup||trade.checklist||'未填 Setup')}</small></td><td>${esc(strategyLabel(trade.strategyVersionId))}</td><td class="${trade.r>0?'pos':trade.r<0?'neg':''}">${missed?'漏單':rLabel(trade)}</td><td><span class="chip ${trade.reviewClass||'pending'}">${classLabel(trade.reviewClass)}</span></td><td class="${gapTotal(trade)?'neg':''}">${gapTotal(trade)?`-${gapTotal(trade).toFixed(2)}R`:'—'}</td><td><button data-edit="${esc(key)}">${trade.reviewClass?'編輯復盤':'開始復盤'}</button></td></tr>`}).join('')}
function renderPatterns(){const all=activeTrades(),values=ATTR.map(([field,label])=>({label,value:all.reduce((sum,trade)=>sum+Math.max(0,Number(trade[field])||0),0)})),total=values.reduce((sum,item)=>sum+item.value,0),max=Math.max(...values.map(item=>item.value),.01);$('#attributionSummary').innerHTML=`<div class="gap-total"><span>已歸因執行損失</span><b>${total?`-${total.toFixed(2)}R`:'—'}</b></div>`+values.map(item=>`<div class="gap-row"><span>${item.label}</span><i><b style="width:${item.value/max*100}%"></b></i><strong>${item.value?`-${item.value.toFixed(2)}R`:'—'}</strong></div>`).join('');const reviewed=all.filter(trade=>trade.reviewClass),counts=Object.keys(CLASS_LABELS).map(key=>({key,label:CLASS_LABELS[key],count:reviewed.filter(trade=>trade.reviewClass===key).length})),countMax=Math.max(...counts.map(item=>item.count),1);$('#classDistribution').innerHTML=counts.map(item=>`<div><span>${item.label}</span><i><b style="width:${item.count/countMax*100}%"></b></i><strong>${item.count}</strong></div>`).join('');const versionIds=[...new Set(reviewed.map(trade=>trade.strategyVersionId||'unassigned'))];$('#strategyQuality').innerHTML=versionIds.length?versionIds.map(id=>{const items=reviewed.filter(trade=>(trade.strategyVersionId||'unassigned')===id),correct=items.filter(trade=>trade.reviewClass==='correct_execution').length,rate=items.length?correct/items.length*100:0;return`<div><span><b>${esc(id==='unassigned'?'未綁定策略':strategyLabel(id))}</b><small>${items.length} 筆已復盤</small></span><strong>${rate.toFixed(1)}%</strong></div>`}).join(''):'<div class="empty-inline">尚無已完成的復盤。</div>'}
function renderLessons(){const items=activeTrades().filter(trade=>trade.review||trade.lesson).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))).slice(0,30);$('#lessonCards').innerHTML=items.length?items.map(trade=>`<article><small>${esc(trade.date||'-')} · ${esc(trade.pair||'-')}</small><b>${classLabel(trade.reviewClass)}</b><p>${esc(trade.review||trade.lesson)}</p><footer><span>${esc(strategyLabel(trade.strategyVersionId))}</span><strong>${gapTotal(trade)?`-${gapTotal(trade).toFixed(2)}R`:'無歸因 R'}</strong></footer></article>`).join(''):'<div class="empty"><b>還沒有復盤結論</b><span>完成第一筆復盤後會整理在這裡。</span></div>'}
function render(){populateControls();metrics();renderRows();renderPatterns();renderLessons()}
function findTrade(key){if(key.startsWith('local:'))return trades.find(trade=>trade.origin==='local'&&String(trade.localId)===key.slice(6));const target=decodeURIComponent(key.slice(9));return trades.find(trade=>trade.origin==='imported'&&trade.baseKey===target)}
function fillStrategies(selected=''){const select=$('#reviewForm [name="strategyVersionId"]');select.innerHTML='<option value="">未綁定策略</option>'+strategies.map(item=>`<option value="${esc(item.id)}">${esc(strategyLabel(item.id))}</option>`).join('');select.value=[...select.options].some(option=>option.value===String(selected||''))?String(selected||''):''}
function openReview(trade=null,missed=false){const form=$('#reviewForm');form.reset();fillStrategies(trade?.strategyVersionId);form.elements.recordKey.value=trade?(trade.origin==='local'?`local:${trade.localId}`:`imported:${encodeURIComponent(trade.baseKey)}`):'';form.elements.origin.value=trade?.origin||'new';['date','time','pair','direction','recordType','setup','reviewClass','review',...ATTR.map(item=>item[0])].forEach(name=>{if(form.elements[name])form.elements[name].value=trade?.[name]??''});if(!trade){form.elements.date.value=new Date().toISOString().slice(0,10);form.elements.time.value=new Date().toTimeString().slice(0,5);form.elements.pair.value='NAS100';form.elements.recordType.value=missed?'missed_opportunity':'trade';form.elements.reviewClass.value=missed?'missed_trade':''}$('#dialogTitle').textContent=missed&&!trade?'記錄符合策略但漏單':'編輯實盤復盤';$('#tradeSummary').textContent=trade?`${trade.date||''} ${trade.pair||''} · ${rLabel(trade)}`:'建立一筆沒有實際下單、但符合策略的機會';const figure=$('#tradeImage');figure.hidden=!trade?.image;if(trade?.image)figure.querySelector('img').src=trade.image;$('#reviewDialog').showModal()}
function toast(message){const node=$('#toast');node.textContent=message;node.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.hidden=true,2400)}
$('#reviewRows').onclick=event=>{const button=event.target.closest('[data-edit]');if(button)openReview(findTrade(button.dataset.edit))};
$('#addMissedTrade').onclick=()=>openReview(null,true);$('#closeDialog').onclick=$('#cancelDialog').onclick=()=>$('#reviewDialog').close();
$('#reviewForm').onsubmit=event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),key=String(data.get('recordKey')||''),numeric=name=>data.get(name)===''?null:Number(data.get(name)),values={date:data.get('date'),year:Number(String(data.get('date')).slice(0,4)),time:data.get('time'),pair:String(data.get('pair')||'').trim().toUpperCase(),direction:data.get('direction'),recordType:data.get('recordType'),strategyVersionId:String(data.get('strategyVersionId')||''),setup:String(data.get('setup')||'').trim(),reviewClass:data.get('reviewClass'),review:String(data.get('review')||'').trim(),...Object.fromEntries(ATTR.map(([field])=>[field,numeric(field)]))};if(values.recordType==='missed_opportunity'){values.reviewClass='missed_trade';values.outcome='be';values.profit=null;values.r=null}if(key.startsWith('local:')){const index=localTrades.findIndex(trade=>String(trade.localId)===key.slice(6));if(index>=0)localTrades[index]={...localTrades[index],...values}}else if(key.startsWith('imported:')){const source=findTrade(key);if(source){deleted.add(source.baseKey);const{id,origin,baseKey:_,...record}=source;localTrades.push({...record,...values,localId:crypto.randomUUID(),batchId:source.batchId||activeBatch||'live-default',source:'Reviewed Import'})}}else localTrades.push({localId:crypto.randomUUID(),batchId:activeBatch==='live-all'?'live-default':activeBatch,source:'Review System',outcome:'be',profit:null,r:null,...values});$('#reviewDialog').close();save();toast('復盤已儲存，主系統會同步讀取。')};
['classFilter','strategyFilter','marketFilter'].forEach(id=>$('#'+id).onchange=renderRows);$('#searchInput').oninput=renderRows;$('#batchSelect').onchange=event=>{activeBatch=event.target.value;localStorage.setItem(KEYS.active,activeBatch);render()};
$$('nav button').forEach(button=>button.onclick=()=>{$$('nav button').forEach(item=>item.classList.toggle('active',item===button));$$('.page').forEach(page=>page.classList.toggle('active',page.id===button.dataset.view));$('#pageTitle').textContent={queue:'實盤復盤工作台',patterns:'執行落差分析',lessons:'復盤結論'}[button.dataset.view]});
mergeTrades();render();
