"use client";

import { useEffect, useMemo, useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowLeft, BarChart3, BookOpenCheck, BrainCircuit, ChevronRight, CircleAlert, FlaskConical, LayoutDashboard, Menu, Plus, Search, SlidersHorizontal, Sparkles, Target, X } from "lucide-react";
import { researchStore } from "./storage";
import { mistakeRecommendations, sampleTrades } from "./data";
import type { ResearchTrade, TradingRule } from "./types";
import "./research.css";

type View = "dashboard" | "journal" | "differences" | "rules" | "mistakes" | "analytics";
const nav: { id:View; label:string; icon:typeof LayoutDashboard }[] = [
  {id:"dashboard",label:"研究總覽",icon:LayoutDashboard},{id:"journal",label:"回測紀錄",icon:FlaskConical},
  {id:"differences",label:"決策差異",icon:BrainCircuit},{id:"rules",label:"Rule Book",icon:BookOpenCheck},
  {id:"mistakes",label:"錯誤資料庫",icon:CircleAlert},{id:"analytics",label:"深度分析",icon:BarChart3},
];
const colors = ["#26d9b5","#ffb43a","#ff647c","#6b8cff","#a77bf3"];

function n(value:number, digits=1){ return Number.isFinite(value) ? value.toFixed(digits) : "0.0"; }
function cnDecision(value:string){ return value === "No Trade" ? "不交易" : value === "Long" ? "做多" : "做空"; }

export default function ResearchApp(){
  const [view,setView]=useState<View>("dashboard");
  const [trades,setTrades]=useState<ResearchTrade[]>(sampleTrades);
  const [rules,setRules]=useState<TradingRule[]>([]);
  const [selected,setSelected]=useState<ResearchTrade|null>(null);
  const [mobileOpen,setMobileOpen]=useState(false);
  const [query,setQuery]=useState("");
  const [market,setMarket]=useState("All");
  const [showForm,setShowForm]=useState(false);

  useEffect(()=>{ setTrades(researchStore.loadTrades()); setRules(researchStore.loadRules()); },[]);
  const saveTrades=(next:ResearchTrade[])=>{setTrades(next);researchStore.saveTrades(next)};
  const stats=useMemo(()=>{
    const wins=trades.filter(t=>t.rMultiple>0), losses=trades.filter(t=>t.rMultiple<0);
    const grossWin=wins.reduce((s,t)=>s+t.rMultiple,0), grossLoss=Math.abs(losses.reduce((s,t)=>s+t.rMultiple,0));
    let sum=0,peak=0,maxDD=0; trades.forEach(t=>{sum+=t.rMultiple;peak=Math.max(peak,sum);maxDD=Math.min(maxDD,sum-peak)});
    return { total:trades.length, winRate:trades.length?wins.length/trades.length*100:0, avg:trades.length?sum/trades.length:0,
      pf:grossLoss?grossWin/grossLoss:grossWin, expectancy:trades.length?sum/trades.length:0, maxDD,
      agreement:trades.length?trades.filter(t=>t.myDecision===t.mambaDecision).length/trades.length*100:0 };
  },[trades]);
  const filtered=useMemo(()=>trades.filter(t=>(market==="All"||t.market===market)&&(`${t.id} ${t.market} ${t.notes} ${t.mistakes.join(" ")}`.toLowerCase().includes(query.toLowerCase()))),[trades,market,query]);
  const diffTrades=filtered.filter(t=>t.myDecision!==t.mambaDecision);
  const equity=useMemo(()=>{let sum=0;return trades.map((t,i)=>({name:t.date.slice(5),value:Number((sum+=t.rMultiple).toFixed(2)),trade:i+1}))},[trades]);
  const mistakeRows=useMemo(()=>Object.entries(trades.flatMap(t=>t.mistakes).reduce<Record<string,ResearchTrade[]>>((a,m)=>{(a[m]??=[]).push(...trades.filter(t=>t.mistakes.includes(m)&&!(a[m]||[]).some(x=>x.id===t.id)));return a},{})).map(([name,items])=>({name,count:items.length,winRate:items.filter(t=>t.rMultiple>0).length/items.length*100,avg:items.reduce((s,t)=>s+t.rMultiple,0)/items.length,last:[...items].sort((a,b)=>b.date.localeCompare(a.date))[0]?.date})).sort((a,b)=>b.count-a.count),[trades]);
  const monthly=useMemo(()=>Object.values(trades.reduce<Record<string,{name:string,r:number}>>((a,t)=>{const k=t.date.slice(0,7);a[k]??={name:k.slice(5)+"月",r:0};a[k].r+=t.rMultiple;return a},{})),[trades]);

  const addTrade=(form:FormData)=>{
    const r=Number(form.get("r")); const mine=String(form.get("mine")) as ResearchTrade["myDecision"]; const mentor=String(form.get("mentor")) as ResearchTrade["mambaDecision"];
    const item:ResearchTrade={id:`BT-${Date.now().toString().slice(-6)}`,date:String(form.get("date")),market:String(form.get("market")),session:String(form.get("session")) as ResearchTrade["session"],setup:String(form.get("setup")) as ResearchTrade["setup"],atr:Number(form.get("atr"))||0,myBias:mine==="No Trade"?"Neutral":mine,myDecision:mine,mambaDecision:mentor,entry:0,stopLoss:0,takeProfit:0,riskReward:Math.abs(r),result:r>0?"Win":r<0?"Loss":"BE",rMultiple:r,confidence:String(form.get("confidence")) as ResearchTrade["confidence"],mistakes:String(form.get("mistakes")||"").split(",").map(s=>s.trim()).filter(Boolean),notes:String(form.get("notes")),lesson:String(form.get("lesson"))};
    saveTrades([item,...trades]);setShowForm(false);
  };

  return <div className="research-shell">
    <aside className={`research-sidebar ${mobileOpen?"open":""}`}>
      <div className="rs-brand"><span>TR</span><div><b>Trading Research</b><small>Decision Intelligence</small></div><button onClick={()=>setMobileOpen(false)}><X size={18}/></button></div>
      <a className="back-link" href="/" aria-label="返回 TradingNote"><ArrowLeft size={16}/> 返回 TradingNote</a>
      <nav>{nav.map(item=>{const Icon=item.icon;return <button className={view===item.id?"active":""} key={item.id} onClick={()=>{setView(item.id);setMobileOpen(false)}}><Icon size={18}/><span>{item.label}</span>{item.id==="differences"&&<em>{trades.filter(t=>t.myDecision!==t.mambaDecision).length}</em>}</button>})}</nav>
      <div className="research-status"><Sparkles size={17}/><div><b>研究循環</b><span>觀察 → 驗證 → 規則化</span></div></div>
    </aside>
    <main className="research-main">
      <header className="research-header"><button className="mobile-menu" onClick={()=>setMobileOpen(true)}><Menu/></button><div><p>TRADING RESEARCH SYSTEM</p><h1>{nav.find(n=>n.id===view)?.label}</h1></div><div className="header-actions"><span className="sample-pill"><span/> 回測樣本 2026-0405</span><button className="primary" onClick={()=>setShowForm(true)}><Plus size={17}/>新增回測</button></div></header>
      {view==="dashboard"&&<Dashboard stats={stats} equity={equity} monthly={monthly} mistakes={mistakeRows} trades={trades}/>} 
      {view==="journal"&&<Journal trades={filtered} query={query} setQuery={setQuery} market={market} setMarket={setMarket} select={setSelected}/>} 
      {view==="differences"&&<Differences trades={diffTrades} select={setSelected}/>} 
      {view==="rules"&&<RuleBook rules={rules} trades={trades} selectTrade={id=>setSelected(trades.find(t=>t.id===id)||null)} update={next=>{setRules(next);researchStore.saveRules(next)}}/>}
      {view==="mistakes"&&<Mistakes rows={mistakeRows}/>} 
      {view==="analytics"&&<Analytics trades={trades} mistakes={mistakeRows}/>} 
    </main>
    {selected&&<TradeDrawer trade={selected} close={()=>setSelected(null)}/>} 
    {showForm&&<TradeForm close={()=>setShowForm(false)} submit={addTrade}/>} 
  </div>;
}

function Dashboard({stats,equity,monthly,mistakes,trades}:{stats:ReturnType<typeof Object>;equity:any[];monthly:any[];mistakes:any[];trades:ResearchTrade[]}){
  const cards=[['Total Trades',stats.total,'筆研究'],['Win Rate',`${n(stats.winRate)}%`,'有效結果'],['Average R',`${stats.avg>=0?'+':''}${n(stats.avg,2)}R`,'每筆期望'],['Profit Factor',n(stats.pf,2),'獲利效率'],['Expectancy',`${n(stats.expectancy,2)}R`,'策略優勢'],['Max Drawdown',`${n(stats.maxDD,2)}R`,'風險區間'],['Mamba Agreement',`${n(stats.agreement)}%`,'決策一致率']];
  const pie=[{name:'Win',value:trades.filter(t=>t.result==='Win').length},{name:'Loss',value:trades.filter(t=>t.result==='Loss').length},{name:'BE',value:trades.filter(t=>t.result==='BE').length}];
  return <div className="page-content"><section className="metric-cards">{cards.map((c,i)=><article key={String(c[0])} className={i===6?'featured':''}><span>{c[0]}</span><strong>{c[1]}</strong><small>{c[2]}</small>{i===6&&<Target size={22}/>}</article>)}</section>
    <section className="chart-grid"><Panel title="Equity Curve" sub="累積 R · 回測樣本"><ResponsiveContainer width="100%" height={310}><AreaChart data={equity}><defs><linearGradient id="eq" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#26d9b5" stopOpacity={0.35}/><stop offset="1" stopColor="#26d9b5" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#26323a" vertical={false}/><XAxis dataKey="name" stroke="#687983" tickLine={false}/><YAxis stroke="#687983" tickLine={false}/><Tooltip contentStyle={tip}/><Area type="monotone" dataKey="value" stroke="#26d9b5" strokeWidth={3} fill="url(#eq)"/></AreaChart></ResponsiveContainer></Panel>
    <Panel title="Monthly R" sub="按月份比較策略表現"><ResponsiveContainer width="100%" height={310}><BarChart data={monthly}><CartesianGrid stroke="#26323a" vertical={false}/><XAxis dataKey="name" stroke="#687983"/><YAxis stroke="#687983"/><Tooltip contentStyle={tip}/><Bar dataKey="r" radius={[6,6,0,0]} fill="#6b8cff"/></BarChart></ResponsiveContainer></Panel></section>
    <section className="chart-grid three"><Panel title="Win / Loss" sub="結果分布"><ResponsiveContainer width="100%" height={220}><PieChart><Pie data={pie} innerRadius={55} outerRadius={82} dataKey="value" paddingAngle={4}>{pie.map((_,i)=><Cell key={i} fill={colors[i]}/>)}</Pie><Tooltip contentStyle={tip}/></PieChart></ResponsiveContainer></Panel><Panel title="Mistake Distribution" sub="最常重複的決策錯誤"><ResponsiveContainer width="100%" height={220}><BarChart data={mistakes.slice(0,5)} layout="vertical"><XAxis type="number" hide/><YAxis type="category" dataKey="name" width={105} tick={{fill:'#8fa1aa',fontSize:11}}/><Bar dataKey="count" fill="#ff647c" radius={4}/></BarChart></ResponsiveContainer></Panel><Panel title="Next Research Focus" sub="系統自動聚焦"><div className="focus-card"><span>01</span><h3>降低與 Mamba 的方向分歧</h3><p>先驗證「高週期方向」與「等待收線」兩條規則，預計可覆蓋 62% 的分歧交易。</p><button>查看相關證據 <ChevronRight size={16}/></button></div></Panel></section>
  </div>;
}

function Journal({trades,query,setQuery,market,setMarket,select}:{trades:ResearchTrade[];query:string;setQuery:(v:string)=>void;market:string;setMarket:(v:string)=>void;select:(t:ResearchTrade)=>void}){return <div className="page-content"><div className="toolbar"><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜尋編號、筆記或錯誤…"/></label><label className="select"><SlidersHorizontal size={16}/><select value={market} onChange={e=>setMarket(e.target.value)}><option>All</option><option>DJ30</option><option>NAS100</option><option>SPX</option></select></label><span>{trades.length} trades</span></div><div className="table-card"><table><thead><tr><th>日期 / ID</th><th>市場</th><th>模型</th><th>我的決策</th><th>Mamba</th><th>一致</th><th>信心</th><th>結果</th><th>錯誤標籤</th></tr></thead><tbody>{trades.map(t=><tr key={t.id} onClick={()=>select(t)}><td><b>{t.date}</b><small>{t.id}</small></td><td>{t.market}<small>{t.session}</small></td><td>{t.setup}<small>ATR {t.atr}</small></td><td>{cnDecision(t.myDecision)}</td><td>{cnDecision(t.mambaDecision)}</td><td><span className={`agreement ${t.myDecision===t.mambaDecision?'yes':'no'}`}>{t.myDecision===t.mambaDecision?'YES':'NO'}</span></td><td><span className={`grade g${t.confidence}`}>{t.confidence}</span></td><td><b className={t.rMultiple>0?'positive':t.rMultiple<0?'negative':''}>{t.rMultiple>0?'+':''}{t.rMultiple}R</b></td><td><div className="tags">{t.mistakes.slice(0,2).map(m=><span key={m}>{m}</span>)}{!t.mistakes.length&&<small>Clean</small>}</div></td></tr>)}</tbody></table></div></div>}

function Differences({trades,select}:{trades:ResearchTrade[];select:(t:ResearchTrade)=>void}){return <div className="page-content"><div className="module-intro"><div><span>DECISION GAP LAB</span><h2>只研究「我和 Mamba 不一樣」的時刻</h2><p>分歧不是錯誤本身，而是最有價值的學習樣本。</p></div><strong>{trades.length}<small>筆決策分歧</small></strong></div><div className="difference-grid">{trades.map(t=><article className="difference-card" key={t.id} onClick={()=>select(t)}><div className="screenshot-placeholder"><span>{t.market}</span><small>{t.date}</small><div className="fake-chart"/></div><div className="decision-compare"><div><small>MY DECISION</small><b>{cnDecision(t.myDecision)}</b></div><i>≠</i><div><small>MAMBA</small><b>{cnDecision(t.mambaDecision)}</b></div></div><p>{t.notes}</p><footer><span className={t.rMultiple>0?'positive':'negative'}>{t.rMultiple>0?'+':''}{t.rMultiple}R</span><span>{t.mistakes[0]||'Execution gap'}</span></footer></article>)}</div></div>}

function RuleBook({rules,trades,selectTrade,update}:{rules:TradingRule[];trades:ResearchTrade[];selectTrade:(id:string)=>void;update:(r:TradingRule[])=>void}){const [active,setActive]=useState(rules[0]?.id);useEffect(()=>{if(!active&&rules[0])setActive(rules[0].id)},[rules,active]);const rule=rules.find(r=>r.id===active)||rules[0];return <div className="page-content"><div className="rule-layout"><section className="rule-list"><div className="section-heading"><div><span>SYSTEM DNA</span><h2>Trading Rule Book</h2></div><button onClick={()=>update([...rules,{id:`R-${String(rules.length+1).padStart(3,'0')}`,title:'新研究規則',description:'填寫這條規則要解決的重複決策問題。',status:'Testing',confidence:50,linkedTrades:[]}])}><Plus size={16}/></button></div>{rules.map(r=><button key={r.id} className={r.id===rule?.id?'active':''} onClick={()=>setActive(r.id)}><span>{r.id}</span><div><b>{r.title}</b><small>{r.linkedTrades.length} evidence · {r.confidence}%</small></div><ChevronRight size={17}/></button>)}</section>{rule&&<section className="rule-detail"><header><div><span className={`rule-status ${rule.status.toLowerCase()}`}>{rule.status}</span><h2>{rule.title}</h2><p>{rule.description}</p></div><div className="confidence-ring" style={{'--value':`${rule.confidence*3.6}deg`} as React.CSSProperties}><b>{rule.confidence}%</b><small>信心</small></div></header><div className="rule-kpis"><div><span>Evidence</span><b>{rule.linkedTrades.length}</b></div><div><span>Winning Cases</span><b>{rule.linkedTrades.filter(id=>trades.find(t=>t.id===id)?.rMultiple!>0).length}</b></div><div><span>Losing Cases</span><b>{rule.linkedTrades.filter(id=>trades.find(t=>t.id===id)?.rMultiple!<0).length}</b></div></div><h3>Linked Evidence</h3><div className="evidence-list">{rule.linkedTrades.map(id=>{const t=trades.find(x=>x.id===id);return t&&<button key={id} onClick={()=>selectTrade(id)}><span className="evidence-thumb">{t.market}</span><div><b>{t.date} · {t.setup}</b><small>{t.lesson}</small></div><strong className={t.rMultiple>0?'positive':'negative'}>{t.rMultiple>0?'+':''}{t.rMultiple}R</strong></button>})}</div><div className="rule-actions"><select value={rule.status} onChange={e=>update(rules.map(r=>r.id===rule.id?{...r,status:e.target.value as TradingRule['status']}:r))}><option>Testing</option><option>Verified</option><option>Discarded</option></select><span>規則狀態會隨驗證持續演進</span></div></section>}</div></div>}

function Mistakes({rows}:{rows:any[]}){return <div className="page-content"><div className="module-intro compact"><div><span>PATTERN RECOGNITION</span><h2>重複錯誤資料庫</h2><p>不是記住每一次虧損，而是消除會重複出現的行為模式。</p></div><strong>{rows.reduce((s,r)=>s+r.count,0)}<small>個錯誤標記</small></strong></div><div className="mistake-list"><div className="mistake-head"><span>排名 / 錯誤</span><span>次數</span><span>勝率</span><span>平均 R</span><span>最後發生</span><span>建議行動</span></div>{rows.slice(0,10).map((r,i)=><div className="mistake-row" key={r.name}><span><i>{String(i+1).padStart(2,'0')}</i><b>{r.name}</b></span><strong>{r.count}</strong><strong>{n(r.winRate)}%</strong><strong className={r.avg>=0?'positive':'negative'}>{n(r.avg,2)}R</strong><span>{r.last}</span><p>{mistakeRecommendations[r.name]||'建立可在進場前檢查的客觀條件。'}</p></div>)}</div></div>}

function Analytics({trades,mistakes}:{trades:ResearchTrade[];mistakes:any[]}){const group=(key:(t:ResearchTrade)=>string)=>Object.values(trades.reduce<Record<string,{name:string,r:number,count:number}>>((a,t)=>{const k=key(t);a[k]??={name:k,r:0,count:0};a[k].r+=t.rMultiple;a[k].count++;return a},{})).map(x=>({...x,avg:x.r/x.count}));const sessions=group(t=>t.session),confidence=group(t=>t.confidence),agreement=group(t=>t.myDecision===t.mambaDecision?'Agreement':'Difference');return <div className="page-content"><section className="analytics-highlights"><article><span>最大虧損錯誤</span><b>{[...mistakes].sort((a,b)=>a.avg-b.avg)[0]?.name}</b><small>{n([...mistakes].sort((a,b)=>a.avg-b.avg)[0]?.avg,2)}R expectancy</small></article><article><span>最有利 Session</span><b>{[...sessions].sort((a,b)=>b.avg-a.avg)[0]?.name}</b><small>{n([...sessions].sort((a,b)=>b.avg-a.avg)[0]?.avg,2)}R / trade</small></article><article><span>最佳 Setup</span><b>{[...group(t=>t.setup)].sort((a,b)=>b.avg-a.avg)[0]?.name}</b><small>樣本模型比較</small></article><article><span>平均 RR</span><b>{n(trades.reduce((s,t)=>s+t.riskReward,0)/trades.length,2)}</b><small>planned reward / risk</small></article></section><section className="chart-grid"><Panel title="Expectancy by Confidence" sub="信心分級是否真的有效"><ResponsiveContainer height={290} width="100%"><BarChart data={confidence}><CartesianGrid stroke="#26323a" vertical={false}/><XAxis dataKey="name" stroke="#687983"/><YAxis stroke="#687983"/><Tooltip contentStyle={tip}/><Bar dataKey="avg" fill="#a77bf3" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></Panel><Panel title="Agreement Edge" sub="與 Mamba 一致時的期望值"><ResponsiveContainer height={290} width="100%"><BarChart data={agreement}><CartesianGrid stroke="#26323a" vertical={false}/><XAxis dataKey="name" stroke="#687983"/><YAxis stroke="#687983"/><Tooltip contentStyle={tip}/><Bar dataKey="avg" fill="#26d9b5" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></Panel></section><Panel title="Decision Difference Trend" sub="依交易序列觀察分歧是否下降"><ResponsiveContainer width="100%" height={260}><LineChart data={trades.map((t,i)=>({i:i+1,gap:t.myDecision===t.mambaDecision?0:1}))}><CartesianGrid stroke="#26323a" vertical={false}/><XAxis dataKey="i" stroke="#687983"/><YAxis domain={[0,1]} ticks={[0,1]} stroke="#687983"/><Tooltip contentStyle={tip}/><Line type="stepAfter" dataKey="gap" stroke="#ffb43a" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></Panel></div>}

function Panel({title,sub,children}:{title:string;sub:string;children:React.ReactNode}){return <section className="panel"><header><div><h3>{title}</h3><p>{sub}</p></div><button>•••</button></header>{children}</section>}
const tip={background:'#12191e',border:'1px solid #2a3840',borderRadius:8,color:'#dce7ea'};

function TradeDrawer({trade,close}:{trade:ResearchTrade;close:()=>void}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="trade-drawer"><header><div><span>{trade.id}</span><h2>{trade.market} · {trade.date}</h2></div><button onClick={close}><X/></button></header><div className="drawer-scroll"><section className="drawer-images"><div><span>BEFORE</span><div className="chart-shot"><div/></div></div><div><span>AFTER</span><div className="chart-shot after"><div/></div></div></section><section className="decision-timeline"><h3>Decision Timeline</h3><div><i>1</i><p><b>My Bias · {trade.myBias}</b><span>{trade.notes}</span></p></div><div><i>2</i><p><b>My Decision · {cnDecision(trade.myDecision)}</b><span>信心等級 {trade.confidence} · {trade.setup} 模型</span></p></div><div><i>3</i><p><b>Mamba · {cnDecision(trade.mambaDecision)}</b><span>{trade.myDecision===trade.mambaDecision?'決策一致':'決策不同，需要建立證據。'}</span></p></div><div><i>4</i><p><b>Outcome · {trade.result}</b><span className={trade.rMultiple>0?'positive':'negative'}>{trade.rMultiple>0?'+':''}{trade.rMultiple}R</span></p></div></section><section className="drawer-note"><span>TODAY&apos;S LESSON</span><p>{trade.lesson}</p></section><section><h3>Mistake Tags</h3><div className="tags large">{trade.mistakes.map(m=><span key={m}>{m}</span>)}{!trade.mistakes.length&&<span className="clean">Clean execution</span>}</div></section><button className="ai-button"><Sparkles size={18}/><span><b>AI Trade Analysis</b><small>預留：截圖分析、Mamba 差異與規則建議</small></span><em>COMING SOON</em></button></div></aside></div>}

function TradeForm({close,submit}:{close:()=>void;submit:(f:FormData)=>void}){return <div className="overlay"><form className="trade-form" action={submit}><header><div><span>NEW RESEARCH SAMPLE</span><h2>新增回測交易</h2></div><button type="button" onClick={close}><X/></button></header><div className="form-grid"><label>日期<input name="date" type="date" required defaultValue="2026-08-01"/></label><label>市場<select name="market"><option>NAS100</option><option>DJ30</option><option>SPX</option></select></label><label>Session<select name="session"><option>New York</option><option>London</option><option>Asia</option></select></label><label>Setup<select name="setup"><option>突破</option><option>回撤</option></select></label><label>我的決策<select name="mine"><option>Long</option><option>Short</option><option>No Trade</option></select></label><label>Mamba 決策<select name="mentor"><option>Long</option><option>Short</option><option>No Trade</option></select></label><label>R Multiple<input name="r" type="number" step=".01" required/></label><label>Confidence<select name="confidence"><option>A</option><option>B</option><option>C</option></select></label><label>ATR<input name="atr" type="number"/></label><label className="wide">Mistake Tags（逗號分隔）<input name="mistakes" placeholder="Breakout Chase, FOMO"/></label><label className="wide">交易筆記<textarea name="notes" rows={3}/></label><label className="wide">Today&apos;s Lesson<textarea name="lesson" rows={3}/></label></div><footer><button type="button" onClick={close}>取消</button><button className="primary">儲存回測</button></footer></form></div>}
