(function(){
  const KEY='tradingnote.partialExitPlan.v1';
  const DEFAULT={enabled:true,legs:[{target:1,weight:.2},{target:2,weight:.1},{target:3,weight:.7}],remainder:'be'};
  const read=()=>{try{const value=JSON.parse(localStorage.getItem(KEY)||'null');return value&&Array.isArray(value.legs)?value:structuredClone(DEFAULT)}catch(_){return structuredClone(DEFAULT)}};
  const normalized=()=>{const settings=read(),legs=settings.legs.map(leg=>({target:Number(leg.target),weight:Number(leg.weight)})).filter(leg=>leg.target>0&&leg.weight>0).sort((a,b)=>a.target-b.target);return{...settings,legs}};
  const realizedR=value=>{const raw=Number(value);if(!Number.isFinite(raw))return null;if(raw<=0)return raw;const settings=normalized();if(!settings.enabled)return raw;const result=settings.legs.reduce((sum,leg)=>sum+(raw>=leg.target?leg.target*leg.weight:0),0);return Math.round(result*1e8)/1e8};
  const describe=()=>normalized().legs.map((leg,index)=>`TP${index+1} ${leg.target}R × ${(leg.weight*100).toFixed(0)}%`).join(' ＋ ');
  function mount(){if(document.querySelector('#partialExitButton'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='../shared/partial-exit.css?v=20260906-2';document.head.appendChild(link);const sidebar=document.querySelector('.sidebar')||document.body;sidebar.insertAdjacentHTML('beforeend',`<div class="partial-exit-sidebar"><small>差異計算條件</small><button id="partialExitButton" class="partial-exit-button" type="button"><span>TP</span><b>分批出場設定</b></button></div>`);document.body.insertAdjacentHTML('beforeend',`<dialog id="partialExitDialog" class="partial-exit-dialog"><form id="partialExitForm"><header><div><small>ANALYSIS EXIT PLAN</small><h2>分批出場設定</h2><p>差異分析會將回測與 Replay 最大 R 換算後，再與實盤成交 R 比較。</p></div><button type="button" data-partial-close>×</button></header><div class="partial-exit-legs"></div><div class="partial-exit-example"></div><p class="partial-exit-note">碰到的 TP 依比例實現；未碰到下一個 TP 的剩餘倉位以 0R（保本）計。負 R 保留原值。</p><footer><button type="button" data-partial-close>取消</button><button class="primary" type="submit">儲存並重新計算</button></footer></form></dialog>`);const dialog=document.querySelector('#partialExitDialog'),form=document.querySelector('#partialExitForm'),legs=form.querySelector('.partial-exit-legs'),example=form.querySelector('.partial-exit-example');
    const render=()=>{const settings=normalized();legs.innerHTML=settings.legs.map((leg,index)=>`<div><b>TP${index+1}</b><label>目標 R<input name="target" type="number" min=".01" step=".01" value="${leg.target}" required></label><label>出場比例<input name="weight" type="number" min=".01" max="1" step=".01" value="${leg.weight}" required></label></div>`).join('');example.innerHTML=`<span>目前公式</span><b>${describe()}</b><small>最大到達 3R → 實現 ${realizedR(3).toFixed(2)}R</small>`};
    document.querySelector('#partialExitButton').onclick=()=>{render();dialog.showModal()};form.querySelectorAll('[data-partial-close]').forEach(button=>button.onclick=()=>dialog.close());form.oninput=()=>{const targets=[...form.querySelectorAll('[name="target"]')].map(input=>Number(input.value)),weights=[...form.querySelectorAll('[name="weight"]')].map(input=>Number(input.value)),total=weights.reduce((sum,value)=>sum+(Number.isFinite(value)?value:0),0);example.innerHTML=`<span>即時計算</span><b>比例合計 ${(total*100).toFixed(0)}%</b><small>最大到達 3R → 實現 ${targets.reduce((sum,target,index)=>sum+(3>=target?target*(weights[index]||0):0),0).toFixed(2)}R</small>`};form.onsubmit=event=>{event.preventDefault();const targets=[...form.querySelectorAll('[name="target"]')].map(input=>Number(input.value)),weights=[...form.querySelectorAll('[name="weight"]')].map(input=>Number(input.value)),total=weights.reduce((sum,value)=>sum+value,0);if(Math.abs(total-1)>.0001){alert(`出場比例必須合計 100%，目前為 ${(total*100).toFixed(0)}%。`);return}localStorage.setItem(KEY,JSON.stringify({enabled:true,legs:targets.map((target,index)=>({target,weight:weights[index]})),remainder:'be'}));dialog.close();window.dispatchEvent(new CustomEvent('tradingnote:partial-exit-change'));};
  }
  window.TradingNotePartialExit={KEY,read:normalized,realizedR,describe,mount};
  if(String(window.location?.pathname||'').includes('/analysis-system/')){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount()}
})();
