import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const source=fs.readFileSync(new URL('../../shared/partial-exit.js',import.meta.url),'utf8');
const storage=new Map();
const sandbox={structuredClone,CustomEvent:class{},localStorage:{getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,value)},window:{addEventListener(){},dispatchEvent(){}},document:{readyState:'loading',addEventListener(){},querySelector(){return null}}};
sandbox.window.window=sandbox.window;
vm.createContext(sandbox);
vm.runInContext(source,sandbox);
const api=sandbox.window.TradingNotePartialExit;
assert.equal(api.realizedR(3),2.5);
assert.equal(api.realizedR(2),.4);
assert.equal(api.realizedR(1),.2);
assert.equal(api.realizedR(-1),-1);
assert.equal(api.realizedR(0),0);
storage.set(api.KEY,JSON.stringify({enabled:true,legs:[{target:1,weight:.5},{target:2,weight:0},{target:3,weight:.5}],remainder:'be'}));
assert.equal(api.realizedR(1),.5);
assert.equal(api.realizedR(2),.5);
assert.equal(api.realizedR(3),2);
assert.equal(api.read().legs.length,3);
assert.equal(api.read().legs[1].weight,0);
assert.match(api.describe(),/TP2 2R × 0%/);
assert.match(source,/name="weight" type="number" min="0"/);
assert.equal(fs.readFileSync(new URL('../../tradingnote-site/public/shared/partial-exit.js',import.meta.url),'utf8'),source);
console.log('Partial exit tests passed');
